sudo: required
services:
  - docker

before_install:
  - docker build -t antonnazarov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antonnazarov/docker-react npm run test -- --coverage
